/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelBazooka(props) {
  const { nodes, materials } = useGLTF('models/Bazooka.glb')

  const material = useMemo(() => {
    if (props.hud) {
      const m = materials.Diffuse_Color.clone()
      m.depthTest = false
      m.depthWrite = false
      m.transparent = true
      return m
    }
    return materials.Diffuse_Color
  }, [materials.Diffuse_Color, props.hud])

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bazooka001.geometry}
        material={material}
        scale={100}
        renderOrder={props.hud ? 999 : 0}
      />
    </group>
  )
}

useGLTF.preload('models/Bazooka.glb')
